spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supergo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: xiaoruan
    driver-class-name: com.mysql.jdbc.Driver